### ISSUE TITLE
Tensorflow model conversion

### ISSUE THREAD

**Issue by AChangXD** [TannerGilbert/OpenCV-AI-Kit-Code-Collection#1]
Hey Tanner,

For running TF models on the OAK devices, what is a good alternative to convert models into .blob format? TF2 doesn't seem to allow exporting to inference graph using the built in export_inference_graph.py script. Have you found any easy workarounds?

**Comment by TannerGilbert** [comment]
Converting Tensorflow 2 models to OpenVino can be quite difficult indeed. I actually haven't tried converting one for quite a while. If you need help, I recommend asking [DepthAI forum](https://discuss.luxonis.com/) or Discord.
